#repo version 2.0.1
name: Remote Testing for Ract 

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  Test-Submit-React-Assessments:
    if: github.repository != 'sabiocode/Starter.react-componentize'
    name: Run Super Duper React Tests
    runs-on: self-hosted
    steps:
      - name: Setting Start Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYY-MM-DDTHH:mm:ssZ'
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: "14.x"

      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        continue-on-error: false

      - name: Show Yarn cache dir
        run: yarn cache dir
        continue-on-error: false

      - uses: actions/checkout@v3
      - name: SET yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir='C:\\yarn-cache'" >> $GITHUB_OUTPUT
        
        
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          #path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Get Current Config
        run: node C:\\sabio_modules\\sabia\\bin\\index.js get-config
        continue-on-error: false

      - name: Copy Admintests 2
        run: node C:\\sabio_modules\\sabia\\bin\\index.js copy-admintests destination="${{github.workspace}}"
        continue-on-error: false

      - name: Yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      # run: yarn install --cache-folder="C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Yarn\Cache\v6" --prefer-offline --network-timeout 600000
        run: yarn install --prefer-offline --network-timeout 600000        
        
      - name: Compile Configured Tests
        run: node C:\\sabio_modules\\sabia\\bin\\index.js compile-configured-test destination="${{github.workspace}}\"
        continue-on-error: false

      - name: Submit Tests to LISA
        run: node C:\\sabio_modules\\sabia\\bin\\index.js send-lisa source="${{github.workspace}}\"
        continue-on-error: false
        
      - name: Send Results to User
        env:
          TIME: "${{ steps.time.outputs.time }}"
        run: node C:\\sabio_modules\\sabia\\bin\\index.js  send-results source="${{github.workspace}}\test-report\reportindex.html" timeStart="${{ steps.time.outputs.time }}"
        continue-on-error: false
