name: Test and Submit

on:
  push:
    branches:
      - "**"
      - "!master"

jobs:
  Test-Submit-React-Assessments:
    name: Set up environment,
    runs-on: windows-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: "14.x"

      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        continue-on-error: false

      - name: Yarn install JS project dependencies
        run: yarn install --prefer-offline --network-timeout 600000

      - name: Yarn Build
        run: yarn build
        continue-on-error: true

      - name: Copy Tests
        run: yarn copy-test

      - name: Run/Compile Tests
        run: yarn compile-test-form
        if: "contains(github.event.head_commit.message, 'Forms v10')"
        continue-on-error: true

      - name: Compile Tests
        run: yarn compile-test-mapping
        if: "contains(github.event.head_commit.message, 'Mapping v12')"
        continue-on-error: true

      - name: Compile Tests
        run: yarn compile-test-form-makeup
        if: "contains(github.event.head_commit.message, 'Forms v7')"
        continue-on-error: true

      - name: Compile Tests
        run: yarn compile-test-mapping-makeup
        if: "contains(github.event.head_commit.message, 'Mapping v11.2')"
        continue-on-error: true

      - name: Compile Tests
        run: yarn compile-test-practice-assessment
        if: "contains(github.event.head_commit.message, 'Practice v2')"
        continue-on-error: true

      - name: Submit test
        run: yarn submit-test ${{ github.event.pusher.name }}
